.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ASTMANPROXY 1 "June  7, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
astmanproxy \- An asterisk manager interface proxy
.SH SYNOPSIS
.B astmanproxy
.RI [ -d ]

.B astmanproxy 
.RI -h

.SH DESCRIPTION
.B astmanproxy 
is a proxy between the manager interface of 
.B asterisk(8)
and other clients. 

The program may do some \fBinteresting\fR \fIthings\fR, but someone else 
needs to write its man page (hint: very simple)

.SH OPTIONS
.B -d
.RS
Debug mode
.RE

.B -h
.RS
Display help message and exit.
.RE

.SH SEE ALSO
.BR asterisk (8)

any reference page?

.SH AUTHOR
astmanproxy was written by David C. Troy <dave@popvox.com>.

This manual page was written by Tzafrir Cohen <tzafrir.cohen@xorcom.com>
